###

GET http://localhost:3000/student

###

GET http://localhost:3000/student?name=Jhon

###

GET http://localhost:3000/student/02221233022

###

POST http://localhost:3000/student 
Content-Type: application/json

{
  "name": "sss",
  "age": 25,
  "_id": "1234"
}


###

PUT http://localhost:3000/student

###

DELETE http://localhost:3000/student

###

GET http://localhost:3000/post